# Generated by Django 2.2.7 on 2019-11-27 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieCode', models.IntegerField()),
                ('title', models.CharField(max_length=150)),
                ('year', models.IntegerField()),
                ('release_date', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('director', models.CharField(max_length=45)),
                ('actors', models.TextField(blank=True, null=True)),
                ('grade', models.CharField(choices=[('전체관람가', '전체관람가'), ('12세이상관람가', '12세이상관람가'), ('15세이상관람가', '15세이상관람가'), ('청소년관람불가', '청소년관람불가')], max_length=20)),
                ('poster_path', models.CharField(blank=True, default='https://', max_length=200, null=True)),
                ('backdrop_path', models.CharField(blank=True, default='https://', max_length=200, null=True)),
                ('youtube_url', models.CharField(blank=True, default='https://', max_length=200, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('genre', models.ForeignKey(choices=[(1, '가족'), (2, '공포(호러)'), (3, '드라마'), (4, '멜로/로맨스'), (5, '미스터리'), (6, '사극'), (7, '스릴러'), (8, '액션'), (9, '어드벤처'), (10, '판타지'), (11, '코미디'), (12, '애니메이션'), (13, '범죄'), (14, '다큐멘터리'), (15, 'SF'), (16, '전쟁'), (17, '공연'), (18, '기타')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.Genre')),
                ('like_users', models.ManyToManyField(blank=True, related_name='like_movies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='NowPlaying20',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='RandYoutube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('score', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
