# Generated by Django 2.2.7 on 2019-11-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='user',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='movies.Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.CharField(blank=True, default='https://', max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='youtube_url',
            field=models.CharField(blank=True, default='https://', max_length=200),
        ),
    ]
